c_stdlib_version:          # [osx and x86_64]
  - "10.15"                # [osx and x86_64]
suffix:
  - ""
  - "-novec"
c_compiler:                # [win]
  - vs2022                 # [win]
cxx_compiler:              # [win]
  - vs2022                 # [win]


# Needs higher stdlib for CUDNN9
# CUDA 12 on aarch needs newer glibc, which requires us to override
# the whole monster zip just to bump c_stdlib_version / docker_image
c_stdlib_version:                                   # [aarch64]
  - 2.17                                            # [aarch64]
  - 2.17                                            # [aarch64]
  - 2.28                                            # [aarch64]
docker_image:                                       # [aarch64]
  - quay.io/condaforge/linux-anvil-cos7-x86_64      # [aarch64]
  - quay.io/condaforge/linux-anvil-cuda:11.8        # [aarch64]
  - quay.io/condaforge/linux-anvil-alma-x86_64:8    # [aarch64]
# rest just to make smithy happy
c_compiler_version:                                 # [aarch64]
  - 13                                              # [aarch64]
  - 11                                              # [aarch64]
  - 12                                              # [aarch64]
cxx_compiler_version:                               # [aarch64]
  - 13                                              # [aarch64]
  - 11                                              # [aarch64]
  - 12                                              # [aarch64]
fortran_compiler_version:                           # [aarch64]
  - 13                                              # [aarch64]
  - 11                                              # [aarch64]
  - 12                                              # [aarch64]
cdt_name:                                           # [aarch64]
  - cos7                                            # [aarch64]
  - cos7                                            # [aarch64]
  - cos7                                            # [aarch64]
cuda_compiler:                                      # [aarch64]
  - None                                            # [aarch64]
  - nvcc                                            # [aarch64]
  - cuda-nvcc                                       # [aarch64]
cuda_compiler_version:                              # [aarch64]
  - None                                            # [aarch64]
  - 11.8                                            # [aarch64]
  - 12.0                                            # [aarch64]
# end override of monster zip
