c_stdlib_version:          # [osx and x86_64]
  - "10.15"                # [osx and x86_64]
suffix:
  - ""
  - "-novec"
c_compiler:                # [win]
  - vs2022                 # [win]
cxx_compiler:              # [win]
  - vs2022                 # [win]

github_actions_labels:          # [win]
- cirun-azure-windows-2xlarge   # [win]
